"""Regenerate frontend/src/production.ts from backend/app/production.py.

The frontend is a VISUALIZER of the box the backend designs, so every number
in ``api.ts::defaultBoxSpec`` has to be the backend's number — that spec is
what the live preview POSTs and what the fab bake ships. They used to be typed
twice, with a comment on each TypeScript copy promising it mirrored a Python
constant; this generator makes the promise mechanical instead, the same way
``gen_assembly_golden.py`` does for the assembly formulas.

    uv run --directory backend python ../tools/dev/gen_production_constants.py

``backend/tests/test_production_constants.py`` renders the file into a temp
path and fails if the checked-in one differs, so a backend constant change
that skips this step is caught by the backend suite rather than by a preview
that quietly disagrees with the plate. Do not hand-edit the TypeScript.

Only the constants the frontend actually needs are emitted. The process
constants (litho floor, finish radius, DBU, polarity, the layer map) are mask
facts with no frontend meaning and stay in Python.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "backend"))

from app.assembly import FoilSpec  # noqa: E402
from app.boxes import PRODUCTION_CARRIER_UM  # noqa: E402
from app.production import (  # noqa: E402
    ART_RIM_UM,
    BAND_UM,
    DEPTH_UM,
    GLASS_MATERIAL,
    GLASS_N,
    HEIGHT_UM,
    MOTIF_SCALE,
    PLY_UM,
    TAPE_UM,
    WIDTH_UM,
)

OUT = Path(__file__).resolve().parents[2] / "frontend" / "src" / "production.ts"

HEADER = """/**
 * GENERATED by tools/dev/gen_production_constants.py from
 * backend/app/production.py. DO NOT HAND-EDIT.
 *
 * The production box, as the backend defines it. `api.ts::defaultBoxSpec`
 * builds its spec from these, so the preview and the fab bake cannot disagree
 * about what the box is. Regenerate after any change to app/production.py:
 *
 *     uv run --directory backend python ../tools/dev/gen_production_constants.py
 *
 * backend/tests/test_production_constants.py fails if this file is stale.
 *
 * All lengths are micrometres.
 */
"""


def _num(v: float) -> str:
    """A float as a TypeScript literal, exactly (repr round-trips)."""
    return repr(float(v))


def render() -> str:
    foil = FoilSpec()
    lines = [HEADER]
    lines.append("/** Outer box dimensions. */")
    lines.append(f"export const WIDTH_UM = {_num(WIDTH_UM)};")
    lines.append(f"export const DEPTH_UM = {_num(DEPTH_UM)};")
    lines.append(f"export const HEIGHT_UM = {_num(HEIGHT_UM)};")
    lines.append("")
    lines.append("/** The stock: one ply per face, and its index at the d-line. */")
    lines.append(f"export const PLY_UM = {_num(PLY_UM)};")
    lines.append(f"export const GLASS_N = {_num(GLASS_N)};")
    lines.append(f"export const GLASS_MATERIAL = '{GLASS_MATERIAL}';")
    lines.append("")
    lines.append("/** 1/4\" copper foil, plus the keep-out and bead the preview draws. */")
    lines.append(f"export const TAPE_UM = {_num(TAPE_UM)};")
    lines.append(f"export const FOIL_SAFETY_UM = {_num(foil.safety_um)};")
    lines.append(f"export const FOIL_BEAD_UM = {_num(foil.bead_um)};")
    lines.append("")
    lines.append("/** Frame dials every face is written at. */")
    lines.append(f"export const MOTIF_SCALE = {_num(MOTIF_SCALE)};")
    lines.append(f"export const BAND_UM = {_num(BAND_UM)};")
    lines.append("")
    lines.append(
        "/** The art rim, PINNED to the 2026-09-15 plate — not derived from the foil. */"
    )
    lines.append(f"export const ART_RIM_UM = {_num(ART_RIM_UM)};")
    lines.append("")
    lines.append(
        "/** Fabricated carrier pitch: one period subtends 0.75 arcmin at 300 mm,\n"
        " *  so the lines are invisible in hand and only the beat shows. */"
    )
    lines.append(f"export const CARRIER_UM = {_num(PRODUCTION_CARRIER_UM)};")
    lines.append("")
    return "\n".join(lines)


def write(path: Path) -> None:
    """Write the rendered module with LF endings (what the rest of
    ``frontend/src`` and Prettier's default use) whatever platform we are on."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render())


def main() -> None:
    write(OUT)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
