"""Regenerate tools/fixtures/assembly_golden.json from the BACKEND assembly
math — the source of truth for the backend<->frontend contract.

The fixture is consumed by BOTH test suites:
  - backend/tests/test_assembly.py::test_golden_fixture_matches_backend
  - frontend/tests/unit/assemblyGolden.test.ts

so any formula drift between app/assembly.py and src/assembly.ts fails one
side's tests instead of silently diverging. Regenerate ONLY when the contract
itself intentionally changes, and re-run both suites afterwards:

    uv run --directory backend python ../tools/dev/gen_assembly_golden.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "backend"))

from app.assembly import (  # noqa: E402
    FoilSpec,
    HingeSpec,
    cut_list,
    hinge_layout,
    keepout_um,
    overlap_um,
    seam_list,
    validate_assembly,
)

OUT = Path(__file__).resolve().parents[1] / "fixtures" / "assembly_golden.json"


def case(
    name: str,
    width_um: float,
    depth_um: float,
    height_um: float,
    glass_thickness_um: float,
    foil: FoilSpec,
    hinge: HingeSpec,
) -> dict:
    try:
        validate_assembly(width_um, depth_um, height_um, glass_thickness_um, foil, hinge)
        valid = True
        error = None
    except ValueError as e:
        valid = False
        error = str(e)

    expected: dict = {"valid": valid}
    if error is not None:
        expected["backend_error"] = error
    if valid:
        expected.update(
            {
                "overlap_um": overlap_um(foil, glass_thickness_um),
                "keepout_um": keepout_um(foil, glass_thickness_um),
                "cut_list": cut_list(width_um, depth_um, height_um, glass_thickness_um),
                "seams": {
                    s["id"]: s["length_um"]
                    for s in seam_list(width_um, depth_um, height_um, glass_thickness_um)
                },
                "hinge": hinge_layout(hinge, width_um),
            }
        )
    return {
        "name": name,
        "spec": {
            "width_um": width_um,
            "depth_um": depth_um,
            "height_um": height_um,
            "glass_thickness_um": glass_thickness_um,
            "foil": foil.to_dict(),
            "hinge": hinge.to_dict(),
        },
        "expected": expected,
    }


def main() -> None:
    cases = [
        case(
            "default-ring-box",
            50000.0, 50000.0, 40000.0, 500.0,
            FoilSpec(),
            HingeSpec(),
        ),
        case(
            "small-box-narrow-tape",
            30000.0, 20000.0, 25000.0, 500.0,
            FoilSpec(tape_width_um=4763.0, safety_um=300.0),
            HingeSpec(segments=7, coverage=0.6),
        ),
        case(
            "thin-glass-mid-tape",
            24000.0, 18000.0, 12000.0, 300.0,
            FoilSpec(tape_width_um=5556.0, safety_um=400.0, bead_um=1500.0, finish="patina"),
            HingeSpec(tube_od_um=2000.0, rod_od_um=1200.0, segments=3, coverage=0.7),
        ),
        # Invalid specs — both validators must reject these.
        case(
            "invalid-tiny-box",
            9000.0, 9000.0, 9000.0, 500.0,
            FoilSpec(),
            HingeSpec(),
        ),
        case(
            "invalid-even-hinge-segments",
            50000.0, 50000.0, 40000.0, 500.0,
            FoilSpec(),
            HingeSpec(segments=4),
        ),
        case(
            "invalid-zero-glass",
            50000.0, 50000.0, 40000.0, 0.0,
            FoilSpec(),
            HingeSpec(),
        ),
        case(
            "invalid-negative-safety",
            50000.0, 50000.0, 40000.0, 500.0,
            FoilSpec(safety_um=-100.0),
            HingeSpec(),
        ),
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps(
            {
                "comment": (
                    "GENERATED by tools/dev/gen_assembly_golden.py from "
                    "backend/app/assembly.py. Consumed by backend AND frontend "
                    "tests to pin the assembly contract. Do not hand-edit."
                ),
                "cases": cases,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(cases)} cases)")


if __name__ == "__main__":
    main()
