/**
 * GENERATED by tools/dev/gen_production_constants.py from
 * backend/app/production.py. DO NOT HAND-EDIT.
 *
 * The production box, as the backend defines it. `api.ts::defaultBoxSpec`
 * builds its spec from these, so the preview and the fab bake cannot disagree
 * about what the box is. Regenerate after any change to app/production.py:
 *
 *     uv run --directory backend python ../tools/dev/gen_production_constants.py
 *
 * backend/tests/test_production_constants.py fails if this file is stale.
 *
 * All lengths are micrometres.
 */

/** Outer box dimensions. */
export const WIDTH_UM = 32000.0;
export const DEPTH_UM = 32000.0;
export const HEIGHT_UM = 35000.0;

/** The stock: one ply per face, and its index at the d-line. */
export const PLY_UM = 2250.0;
export const GLASS_N = 1.4585;
export const GLASS_MATERIAL = 'fused quartz';

/** 1/4" copper foil, plus the keep-out and bead the preview draws. */
export const TAPE_UM = 6350.0;
export const FOIL_SAFETY_UM = 500.0;
export const FOIL_BEAD_UM = 2000.0;

/** Frame dials every face is written at. */
export const MOTIF_SCALE = 0.68;
export const BAND_UM = 2400.0;

/** The art rim, PINNED to the 2026-09-15 plate — not derived from the foil. */
export const ART_RIM_UM = 3637.5;

/** Fabricated carrier pitch: one period subtends 0.75 arcmin at 300 mm,
 *  so the lines are invisible in hand and only the beat shows. */
export const CARRIER_UM = 65.5;
